### ISSUE TITLE
Fix problem of private video in download function : download_playlist()

### ISSUE THREAD

**Issue by hduss** [hduss/youtube-s-thief#1]
#### Bug
```
Traceback (most recent call last):
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 336, in <module>
    main()
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 312, in main
    download_playlist(selected_file['title'], file_format)
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 149, in download_playlist
    print(yt.title)
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\pytube\__main__.py", line 341, in title
    self.check_availability()
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\pytube\__main__.py", line 224, in check_availability
    raise exceptions.VideoPrivate(video_id=self.video_id)
pytube.exceptions.VideoPrivate: kMGD6cmQBDw is a private video
```

#### Description
Function download playlist() return error because some videos are private

#### Files
Error in main.py

**Comment by hduss** [comment]
### 2 options
- Continue when private video is find and store them in folder to download in another way
- Find way to download private videos

**Comment by hduss** [comment]
Chosen option => 
Add try on availability of video : 
```
  try:
      yt = YouTube(url)
      yt.check_availability()  # test availability on url
  except:
      counter_corrupt_videos += 1
```

Skip video and add counter to see how many videos are skipped
