### ISSUE TITLE
Restricted age videos

### ISSUE THREAD

**Issue by hduss** [hduss/youtube-s-thief#3]
Some videos are age restricted, need to find a way around the problem

The probleme exist with pytube :
```
Traceback (most recent call last):
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 367, in <module>
    main()
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 329, in main
    download_playlist(selected_file['title'], file_format)
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 160, in download_playlist
    stream = yt.streams.filter(only_audio=True).first()
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\pytube\__main__.py", line 172, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\pytube\__main__.py", line 156, in streaming_data
    self.bypass_age_gate()
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\pytube\__main__.py", line 260, in bypass_age_gate
    raise exceptions.AgeRestrictedError(self.video_id)
pytube.exceptions.AgeRestrictedError: uFnlCzgThS8 is age restricted, and can't be accessed without logging in.
```

 and youtube-dl : 
```
Traceback (most recent call last):
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 367, in <module>
    main()
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 346, in main
    result = ydl.extract_info(
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 824, in wrapper
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
```

**Comment by hduss** [comment]
Often the problem is related to the video clip
Maybe search video without clip to launch download

**Comment by hduss** [comment]
For now, corrupted videos (no available or age restricted) are saved in a list
