### ISSUE TITLE
Recuring error

### ISSUE THREAD

**Issue by hduss** [hduss/youtube-s-thief#4]
Sometimes this error pop : 

```
Traceback (most recent call last):
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 400, in <module>

  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 330, in main
    file_format = input('Please enter the format (leave blank for mp3) : ')
  File "C:\Users\Dumuzhy\Desktop\Dev\python\youtubeList\main.py", line 169, in download_playlist
    out_file = stream.download(output_path='downloads/' + folder_name)
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'C:\\Users\\Dumuzhy\\Desktop\\Dev\\python\\youtubeList\\downloads/Liked videos\\Damso - N J Respect R.mp4' -> 'C:\\Users\\Dumuzhy\\Desktop\\Dev\\python\\youtubeList\\downloads/Liked videos\\Damso - N J Respect R.mp3'
```

See when Youtube.download() and os.rename() in download_playlist() function

**Comment by hduss** [comment]
I think the problem came from name of file OR from initial extension (youtube.streams())

**Comment by hduss** [comment]
The roblem came from '.' in file name => Fix by replace('.', '')
